language: python
install:
  - pip install -v docutils

script:
  - mkdir html
  - cd CPEUM
  - rst2html.py toc.rst ../html/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local-dir: html
  verbose: true
  on:
    branch: master
