name: BlueSky

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  bluesky:

    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    environment:
      name: BlueSky

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if last commit in PR contains document changes
        run: |
          git show --name-only --oneline HEAD | head -1 | grep -i -e "artículo" -e "articulo"
          git show --name-only --oneline HEAD | tail -n +2 | grep "^CPEUM/.*\.rst$"

      - name: Extract second paragraph of commit log if previous step was successful
        if: success()
        id: desc
        run: |
          git show --summary --format=%B HEAD | awk -v RS='(\r?\n){2,}' 'NR == 2 { print "desc=" $RS }' | sed ':a;N;$!ba;s/\n/ /g' >> "$GITHUB_OUTPUT"

      # Announce merge of the pull request in BlueSky
      - name: Post in BlueSky
        if: success()
        uses: zentered/bluesky-post-action@v0.2.0
        with:
          post: |
            ${{ steps.desc.outputs.desc }}

            ${{ github.event.pull_request._links.html.href }}
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
