# This is a basic workflow to help you get started with Actions

name: CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install aspell aspell-es

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

        # Runs a single command using the runners shell
      - name: Install python dependencies
        run: "python3 -m pip install docutils"

      - name: Check spelling
        run: "bash scripts/spellcheck.sh check"

      # Runs a set of commands using the runners shell
      - name: Generate document
        run: |
          mkdir html
          cd CPEUM
          rst2html.py toc.rst ../html/index.html

      # Install generated document in Pages
      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: html
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
